name: Build and Test Angular

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build
  docker:
    runs-on: ubuntu-latest
    needs: build  # ← seulement si le build passe !
    if: github.ref == 'refs/heads/main'  # ← seulement sur main
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Angular image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/peemers/covaldys-angular:latest
            ghcr.io/peemers/covaldys-angular:${{ github.sha }}
